# Generated by Django 5.2.7 on 2026-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('FLU', 'Flu'), ('COLD', 'Common Cold'), ('ASTHMA', 'Asthma'), ('DIABETES', 'Diabetes'), ('HYPERTENSION', 'Hypertension'), ('COVID', 'COVID-19'), ('OTHER', 'Other')], max_length=20)),
                ('doctor_notes', models.TextField(blank=True)),
                ('date_of_visit', models.DateField(auto_now_add=True)),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
