# Generated by Django 5.2.7 on 2026-03-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('treatment_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('medicine_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('room_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('lab_tests', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='records.medicalrecord')),
            ],
        ),
    ]
